name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      USER: ${{ secrets.USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files via Rsync
        run: |
          rsync -avz --delete \
            --exclude 'node_modules/' \
            --exclude '.env' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            $USER@$SERVER_IP:$REMOTE_DIR/

          ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP "cd $REMOTE_DIR && npm install && systemctl restart tiktok-tg-downloader" \
